src/Weather.MVC/Models/ErrorViewModel.cs
namespace Weather.MVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/Weather.MVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Weather.MVC.Models;

namespace Weather.MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/Weather.MVC/Controllers/LoadArchiveController.cs
using Microsoft.AspNetCore.Mvc;
using NPOI.SS.UserModel;
using NPOI.XSSF.UserModel;
using Weather.MVC.Models;
using Weather.Services.Services;

namespace Weather.MVC.Controllers;

public class LoadArchiveController : Controller
{
    private readonly IWeatherParser _weatherParser;

    public LoadArchiveController(IWeatherParser weatherParser)
    {
        _weatherParser = weatherParser;
    }

    public ActionResult Index()
    {
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Create(IFormCollection collection)
    {
        IFormFile? formFile = null;
        try
        {
            foreach (var file in collection.Files)
            {
                formFile = file;
                using var stream = file.OpenReadStream();
                _weatherParser.Parse(stream);
            }
            return View(nameof(Index), "Files uploaded successfully");
        }
        catch (Exception exc)
        {
            string message = formFile is null ? exc.Message : $"Error in file: {formFile.FileName}. " + exc.Message;
            return View(nameof(Index), message);
        }
    }
}

src/Weather.MVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "DynamicSun";
}

<div class="text-center">
    <h1 class="display-4">DynamicSun</h1>
    <p>Тестовое задание</p>
</div>

src/Weather.MVC/Views/LoadArchive/Index.cshtml
@model string
@{
    ViewData["Title"] = "Загрузка";
}
<h3>Выберите файлы для загрузки</h3>
<form asp-controller="LoadArchive" asp-action="Create" method="post" enctype="multipart/form-data">
    <div class="form-group">
        <input class="form-control-file"
               type="file"
               accept="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel"
               name="uploadedFile"
               multiple
               onchange="return DisplayLoadingMessage(this);" />
    </div>
</form>
<p class="message">@Model</p>
<p class="load hidden">Loading...</p>

@section Scripts{
    <script type="text/javascript">
        function DisplayLoadingMessage(input) {
            event.preventDefault();
            $(".load").removeClass("hidden");
            $(".message").addClass("hidden");
            input.form.submit();
            $(input).prop("disabled", true);
        }
    </script>
}

src/Weather.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Weather</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Weather.MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Weather</a> 
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Архив</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="LoadArchive" asp-action="Index">Загрузка</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Weather
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>